# Generated by Django 5.0 on 2024-04-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_Name', models.CharField(max_length=100)),
                ('Business_bio', models.TextField(blank=True, null=True)),
                ('Business_Logo', models.ImageField(upload_to='')),
                ('Business_Contact', models.CharField(max_length=100)),
                ('Business_Email', models.CharField(max_length=100)),
                ('Business_Opening_Time', models.CharField(max_length=100)),
                ('Business_Address', models.CharField(max_length=100)),
                ('Facebook_Link', models.CharField(blank=True, max_length=500, null=True)),
                ('Instagram_Link', models.CharField(blank=True, max_length=500, null=True)),
                ('Whatsapp_Link', models.CharField(blank=True, max_length=500, null=True)),
                ('About_us', models.TextField(blank=True, null=True)),
                ('TermsConditions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=100)),
                ('departure', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.CharField(max_length=100)),
                ('Round_trip', models.BooleanField(default=False)),
                ('return_date', models.CharField(blank=True, default='N/A', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='new_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.CharField(max_length=100)),
                ('client_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('client_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='client_contact',
        ),
    ]
