# Generated by Django 5.0.1 on 2024-04-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0002_airport_businessinfo_flight_request_new_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight_request',
            name='Adult',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight_request',
            name='Children',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight_request',
            name='Infant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
