# Generated by Django 5.0 on 2024-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0007_package_delete_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='deals_event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_title', models.CharField(blank=True, max_length=300, null=True)),
                ('deal_poster', models.ImageField(blank=True, null=True, upload_to='poster')),
            ],
        ),
    ]
