# Generated by Django 5.0 on 2024-04-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0010_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
