# Generated by Django 5.0 on 2024-04-12 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0012_exclusion_inclusion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deals_event',
            options={'verbose_name': 'Event Posters', 'verbose_name_plural': 'Event Posters'},
        ),
        migrations.AlterModelOptions(
            name='exclusion',
            options={'verbose_name': 'Package Exclusions', 'verbose_name_plural': 'Package Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='flight_request',
            options={'verbose_name': 'Customer Flight Request', 'verbose_name_plural': 'Customer Flight Request'},
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'verbose_name': 'Package Highlights', 'verbose_name_plural': 'Package Highlights'},
        ),
        migrations.AlterModelOptions(
            name='inclusion',
            options={'verbose_name': 'Package Inclusions', 'verbose_name_plural': 'Package Inclusions'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': 'Package Itinerary', 'verbose_name_plural': 'Package Itinerary'},
        ),
        migrations.AlterModelOptions(
            name='new_contact',
            options={'verbose_name': 'Customer Inquiries', 'verbose_name_plural': 'Customer Inquiries'},
        ),
        migrations.AddField(
            model_name='flight_request',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
