# Generated by Django 5.0 on 2024-04-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0015_company_members_is_admin_company_members_is_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company_Members',
        ),
    ]
