# Generated by Django 5.0 on 2024-04-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0017_company_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight_request',
            name='Adult',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight_request',
            name='Children',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight_request',
            name='Infant',
            field=models.CharField(blank=True, default='0', max_length=100, null=True),
        ),
    ]
