# Generated by Django 5.0 on 2024-04-21 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0018_alter_flight_request_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_contact',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
