# Generated by Django 5.0 on 2024-04-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0019_new_contact_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='location_desc',
        ),
        migrations.AlterField(
            model_name='package',
            name='country_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='location_image',
            field=models.ImageField(null=True, upload_to='packages_image'),
        ),
        migrations.AlterField(
            model_name='package',
            name='location_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
