# Generated by Django 5.0.1 on 2024-04-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0022_quotation_fill_itinerary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(blank=True, editable=False, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('client_email', models.CharField(blank=True, max_length=300, null=True)),
                ('per_adult', models.IntegerField(blank=True, null=True)),
                ('per_child', models.IntegerField(blank=True, null=True)),
                ('per_infant', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
