# Generated by Django 5.0.1 on 2024-04-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0023_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='q_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
