# Generated by Django 5.0.1 on 2024-04-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0024_alter_quotation_q_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotation',
        ),
    ]
