# Generated by Django 5.0.1 on 2024-04-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0026_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation_itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('day', models.TextField(blank=True, max_length=300, null=True)),
                ('Itinerary', models.TextField(blank=True, null=True)),
                ('Meals', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
