# Generated by Django 5.0.1 on 2024-04-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0027_quotation_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation_inclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(blank=True, null=True)),
                ('inclu', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
