# Generated by Django 5.0.1 on 2024-04-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0028_quotation_inclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation_airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(blank=True, null=True)),
                ('airlns', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='quotation_hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.IntegerField(blank=True, null=True)),
                ('hotels', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
