# Generated by Django 5.0.1 on 2024-04-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0029_quotation_airlines_quotation_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='num_adult',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='num_child',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='num_infant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
