# Generated by Django 5.0.1 on 2024-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0031_quotation_hotels_airlns'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='package_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
