# Generated by Django 5.0 on 2024-04-26 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0032_quotation_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
