# Generated by Django 3.2.25 on 2024-04-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0033_quotation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
