# Generated by Django 5.0 on 2024-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0036_rename_url_deals_event_deal_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
    ]
