# Generated by Django 5.0.6 on 2024-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0037_package_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inclusion',
            options={'verbose_name': 'Package Inclusions and Exclusion', 'verbose_name_plural': 'Package Inclusions and Exclusions'},
        ),
        migrations.AddField(
            model_name='inclusion',
            name='exclusion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
