# Generated by Django 5.0.6 on 2024-05-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0038_alter_inclusion_options_inclusion_exclusion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inclusion',
            options={'verbose_name': 'Package Inclusions', 'verbose_name_plural': 'Package Inclusions'},
        ),
        migrations.RemoveField(
            model_name='inclusion',
            name='exclusion',
        ),
    ]
