# Generated by Django 5.0.6 on 2024-05-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0039_alter_inclusion_options_remove_inclusion_exclusion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation_inclusion',
            options={'verbose_name': 'Quotation Inclusion and Exclusion', 'verbose_name_plural': 'Quotation Inclusions and Exclusions'},
        ),
        migrations.AddField(
            model_name='quotation_inclusion',
            name='exclu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
