# Generated by Django 5.0.6 on 2024-05-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0040_alter_quotation_inclusion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotation_fill_Exclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclusion', models.TextField()),
            ],
        ),
    ]
