# Generated by Django 5.0.6 on 2024-05-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0041_quotation_fill_exclusion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='quotation_itinerary',
        ),
    ]
