# Generated by Django 5.0.6 on 2024-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app1', '0043_quotation_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation_itinerary',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
